version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: oumaymaselmi/devops-project:latest
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ta_db
    depends_on:
      - mongodb

volumes:
  mongo-data:
